### ISSUE TITLE
Compilation issues on linux and OS X

### ISSUE THREAD

**Issue by johnlees** [imartayan/CBL#2]
I'm excited to try this library, it looks great

However I've gotten stuck compiling on two machines, if you had any advice that would be great

Fedora 38
========
Running `cargo +nightly build` throws an issue in autocxx-bindgen:
```
  thread 'main' panicked at /home/jlees/.cargo/registry/src/index.crates.io-6f17d22bba15001f/autocxx-bindgen-0.65.1/ir/context.rs:1997:26:
  Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))
```
This is with libstdc++-13

OS X
====
I wasn't sure if OS X is supported or not, but on an M1 mac I get:
```
CXXFLAGS = Some("-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0)
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "x86_64-apple-darwin13.4.0-clang++" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "--target=arm64-apple-darwin" "-march=core2" "-mtune=haswell" "-mssse3" "-ftree-vectorize" "-fPIC" "-fstack-protector-strong" "-O2" "-pipe" "-stdlib=libc++" "-fvisibility-inlines-hidden" "-fmessage-length=0" "-o" "/Users/jlees/Documents/EBI/SKA project/CBL/target/debug/build/link-cplusplus-352f80a998321554/out/669417d7ccbf6cde-dummy.o" "-c" "/Users/jlees/Documents/EBI/SKA project/CBL/target/debug/build/link-cplusplus-352f80a998321554/out/dummy.cc"
  cargo:warning=x86_64-apple-darwin13.4: error: unsupported argument 'core2' to option '-march='
```
I couldn't work out if it was possible to remove the `march` option (which is in both CFLAGS and CXXFLAGS). I tried removing it from `build.rs` but it made no difference

**Comment by imartayan** [comment]
Thanks for the detailed report, I'll try to figure out how to fix this next week

**Comment by johnlees** [comment]
But can confirm I've got it running on ubuntu (multipass on OS X)

> Thanks for the detailed report, I'll try to figure out how to fix this next week

Thanks! Sorry for posting at the weekend

**Comment by imartayan** [comment]
Hi @johnlees,
I couldn't reproduce your issue on my M1 mac (running macOS 14.2.1), I tried on a fresh session with the default clang compiler provided by Apple (version 15) and with the clang compiler provided by homebrew (version 17) and it worked with both.

Can you tell me more about your setup?
- what version of macOS are you running?
- which clang compiler are you using?

And can you give me the output of the following commands?
```sh
which clang
clang --version
echo $CC
echo $CXX
echo $CPPFLAGS
echo $LDFLAGS
```

**Comment by imartayan** [comment]
I was able to build CBL on a fresh Fedora 39 after installing the following package:
```sh
sudo dnf install -y clang15-devel
```
@johnlees can you tell me if this solves your issue?

**Comment by johnlees** [comment]
> I was able to build CBL on a fresh Fedora 39 after installing the following package:
> 
> ```shell
> sudo dnf install -y clang15-devel
> ```
> 
> @johnlees can you tell me if this solves your issue?

Unfortunately not, still the same issue. As I've got this working on ubuntu I'm happy to drop this but will just paste the relevant issues in autocxx I saw in case useful for anyone in the future:
- https://github.com/rust-lang/rust-bindgen/issues/2500
- https://github.com/google/autocxx/issues/1327

> Hi @johnlees, I couldn't reproduce your issue on my M1 mac (running macOS 14.2.1), I tried on a fresh session with the default clang compiler provided by Apple (version 15) and with the clang compiler provided by homebrew (version 17) and it worked with both.
> 
> Can you tell me more about your setup?
> 
>     * what version of macOS are you running?
> 
>     * which clang compiler are you using?
> 
> 
> And can you give me the output of the following commands?
> 
> ```shell
> which clang
> clang --version
> echo $CC
> echo $CXX
> echo $CPPFLAGS
> echo $LDFLAGS
> ```

I think with the previous issue I was using a version of clang from conda, now using the system one
```
which clang
/usr/bin/clang

clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
none of the makevars are set in env

With a new build:
```
git clone --recursive git@github.com:imartayan/CBL.git
cargo +nightly build
```

I'm now getting a different error:
```
   Compiling cbl v0.1.0 (/Users/jlees/Documents/EBI/SKA project/CBL)
error[E0599]: no method named `chunk_by` found for struct `Vec<(usize, SlicedInt<{ SUFFIX_BITS.div_ceil(8) }>)>` in the current scope
   --> src/wordset/mod.rs:133:40
    |
133 |         for group in prefixes_suffixes.chunk_by(|(p1, _), (p2, _)| p1 == p2) {
    |                                        ^^^^^^^^ help: there is a method with a similar name: `chunks`

error[E0599]: no method named `chunk_by` found for struct `Vec<(usize, SlicedInt<{ SUFFIX_BITS.div_ceil(8) }>)>` in the current scope
   --> src/wordset/mod.rs:158:40
    |
158 |         for group in prefixes_suffixes.chunk_by(|(p1, _), (p2, _)| p1 == p2) {
    |                                        ^^^^^^^^ help: there is a method with a similar name: `chunks`

error[E0599]: no method named `chunk_by` found for struct `Vec<(usize, SlicedInt<{ SUFFIX_BITS.div_ceil(8) }>)>` in the current scope
   --> src/wordset/mod.rs:178:40
    |
178 |         for group in prefixes_suffixes.chunk_by(|(p1, _), (p2, _)| p1 == p2) {
    |                                        ^^^^^^^^ help: there is a method with a similar name: `chunks`

error[E0599]: no method named `chunk_by` found for struct `Vec<(usize, SlicedInt<{ SUFFIX_BITS.div_ceil(8) }>)>` in the current scope
   --> src/wordset/mod.rs:209:40
    |
209 |         for group in prefixes_suffixes.chunk_by(|(p1, _), (p2, _)| p1 == p2) {
    |                                        ^^^^^^^^ help: there is a method with a similar name: `chunks`
```

**Comment by imartayan** [comment]
Alright, this new error is just due to your Rust version (CBL requires 1.77+), just update it with `rustup update` and you should be fine!

**Comment by johnlees** [comment]
Ah apologies I had missed that requirement!

Yes all working now, thanks for the help!!
