### ISSUE TITLE
Reverse complements

### ISSUE THREAD

**Issue by PavelVesely** [imartayan/CBL#3]
Dear @imartayan , very nice work on data structures for k-mers!
I'm currently working on some experiments that include CBL. However, I realized that in some cases, reverse complements are probably not handled correctly (namely, when all queries supposed to be positive, only about a half of them were reported as positive by CBL).

I've created the following setup to reproduce the issue: I compiled CBL (with default K and PREFIX_BITS) and built an index on the [S. pneumoniae pangenome](https://github.com/karel-brinda/masked-superstrings-supplement/blob/main/data/spneumo_pangenome_k32.fa.xz):
```
$ ../CBL/target/release/examples/cbl build -o spneumo_pangenome_k32.fa.cbl spneumo_pangenome_k32.fa
```
Then I created the following query file:
```
$ cat query.k_25.fa
>q1
CTTTATAGTCTGAAAAAAGGTAACC
>q2 = reverse complement of q1
GGTTACCTTTTTTCAGACTATAAAG
```
and ran CBL query:
```
$ ../CBL/target/release/examples/cbl query spneumo_pangenome_k32.fa.cbl query.k_25.fa
Reading the index stored in spneumo_pangenome_k32.fa.cbl
Querying the 25-mers contained in query.k_25.fa
# queries: 2
# positive queries: 1 (50.00%)
```
I would appreciate if you could look into this issue.

**Comment by imartayan** [comment]
Hello @PavelVesely, thanks for reporting this issue, I was able to reproduce it with your example!
I built the CLI mostly as a prototype to show the main features of the library and some options are still missing. In particular, it currently does not canonize k-mers when building the index, which is why only half of the queries are positive in this case.
I'm a bit busy right now, but I'll try to add an option in the CLI to use canonical k-mers this week.

**Comment by PavelVesely** [comment]
Thanks for the answer! Now the results I'm getting make sense to me. The missing support for canonical k-mers is not an urgent issue for me, though it may be useful to make it clear in the README (I didn't find it, so based on reading the paper, I was assuming CBL is adding canonical k-mers to the index).

**Comment by imartayan** [comment]
Hello @PavelVesely, I've added a new option to the CLI to use canonical k-mers in the index! To use it, just add `-c` to the build command.

**Comment by PavelVesely** [comment]
Excellent, thanks!
